import { logoType } from '@/app/common.types';

export const logoSlide: string[] = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'Next.js',
  'React',
  'Hardhat',
  'Redux',
  'Bootstrap',
  'Tailwind',
  'Sass',
  'Git',
  'PostgreSQL',
  'Node.js',
  'Supabase',
  'Cloudinary',
  'WordPress',
  'Figma',
  'Photoshop',
  'InDesign',
  'Illustrator',
];
