// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  blockquote: dynamic(() => import('./Blockquote')),
  code_slice: dynamic(() => import('./CodeSlice')),
  hero: dynamic(() => import('./Hero')),
  image_slice: dynamic(() => import('./ImageSlice')),
  rich_text: dynamic(() => import('./RichText')),
  tips_tricks: dynamic(() => import('./TipsTricks')),
};
