// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice =
  | TipsTricksSlice
  | BlockquoteSlice
  | CodeSliceSlice
  | ImageSliceSlice
  | RichTextSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Publication Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publication_date: prismic.DateField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    'blog_post',
    Lang
  >;

type PageDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

export type AllDocumentTypes = BlogPostDocument | PageDocument;

/**
 * Primary content in *Blockquote → Default → Primary*
 */
export interface BlockquoteSliceDefaultPrimary {
  /**
   * Blockquote Richtext field in *Blockquote → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockquote.default.primary.blockquote_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blockquote_richtext: prismic.RichTextField;
}

/**
 * Default variation for Blockquote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockquoteSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlockquoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blockquote*
 */
type BlockquoteSliceVariation = BlockquoteSliceDefault;

/**
 * Blockquote Shared Slice
 *
 * - **API ID**: `blockquote`
 * - **Description**: Blockquote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockquoteSlice = prismic.SharedSlice<
  'blockquote',
  BlockquoteSliceVariation
>;

/**
 * Primary content in *CodeSlice → Default → Primary*
 */
export interface CodeSliceSliceDefaultPrimary {
  /**
   * language field in *CodeSlice → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: code lang
   * - **Default Value**: typescript
   * - **API ID Path**: code_slice.default.primary.language
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  language: prismic.SelectField<
    | 'typescript'
    | 'javascript'
    | 'python'
    | 'json'
    | 'html'
    | 'css'
    | 'bash'
    | 'structure'
    | 'table',
    'filled'
  >;

  /**
   * title field in *CodeSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * codeblock field in *CodeSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code_slice.default.primary.codeblock
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  codeblock: prismic.RichTextField;
}

/**
 * Default variation for CodeSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CodeSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CodeSlice*
 */
type CodeSliceSliceVariation = CodeSliceSliceDefault;

/**
 * CodeSlice Shared Slice
 *
 * - **API ID**: `code_slice`
 * - **Description**: CodeSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeSliceSlice = prismic.SharedSlice<
  'code_slice',
  CodeSliceSliceVariation
>;

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *ImageSlice → Default → Primary*
 */
export interface ImageSliceSliceDefaultPrimary {
  /**
   * image field in *ImageSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * description field in *ImageSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageSlice*
 */
type ImageSliceSliceVariation = ImageSliceSliceDefault;

/**
 * ImageSlice Shared Slice
 *
 * - **API ID**: `image_slice`
 * - **Description**: ImageSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceSlice = prismic.SharedSlice<
  'image_slice',
  ImageSliceSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  'rich_text',
  RichTextSliceVariation
>;

/**
 * Primary content in *TipsTricks → Default → Primary*
 */
export interface TipsTricksSliceDefaultPrimary {
  /**
   * Option field in *TipsTricks → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: tips
   * - **API ID Path**: tips_tricks.default.primary.option
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  option: prismic.SelectField<'tips' | 'question' | 'warn', 'filled'>;

  /**
   * Tips field in *TipsTricks → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tips_tricks.default.primary.tips
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tips: prismic.RichTextField;
}

/**
 * Default variation for TipsTricks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TipsTricksSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TipsTricksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TipsTricks*
 */
type TipsTricksSliceVariation = TipsTricksSliceDefault;

/**
 * TipsTricks Shared Slice
 *
 * - **API ID**: `tips_tricks`
 * - **Description**: TipsTricks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TipsTricksSlice = prismic.SharedSlice<
  'tips_tricks',
  TipsTricksSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlockquoteSlice,
      BlockquoteSliceDefaultPrimary,
      BlockquoteSliceVariation,
      BlockquoteSliceDefault,
      CodeSliceSlice,
      CodeSliceSliceDefaultPrimary,
      CodeSliceSliceVariation,
      CodeSliceSliceDefault,
      HeroSlice,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageSliceSlice,
      ImageSliceSliceDefaultPrimary,
      ImageSliceSliceVariation,
      ImageSliceSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TipsTricksSlice,
      TipsTricksSliceDefaultPrimary,
      TipsTricksSliceVariation,
      TipsTricksSliceDefault,
    };
  }
}
